/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "hi_javafx"

include("appJava")
project(":appJava").projectDir = file("AppJava/app")

include("appKt")
project(":appKt").projectDir = file("AppKt/app")


include("appFX")
project(":appFX").projectDir = file("app")

