/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"

struct TEST *
test_proc_2_svc(struct TEST *argp, struct svc_req *rqstp)
{
	static struct TEST  result;

	/*
	 * insert server code here
	 *//* -<<< Add to test*/
	switch(argp->op){
	case ADD:
	    result.result = argp->arg1 + argp->arg2;
	break;
	case SUB:
	    result.result = argp->arg1 - argp->arg2;
	break;
	case MUL:
	    result.result = argp->arg1 * argp->arg2;
        break;
	case DIV:
	    result.result = argp->arg1 / argp->arg2;
	break;
	default:
	break;
	}
	/* -<<< Add to test*/

	return &result;
}
