/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"


void
test_prog_2(char *host)
{
	CLIENT *clnt;
	struct TEST  *result_1;
	struct TEST  test_proc_2_arg;

        char c;
        
        printf("choose the operation:\n\t0---ADD\n\t1---SUB\n\t2---MUL\n\t3---DIV\n");
        c = getchar();
        switch(c) {
            case '0':
                test_proc_2_arg.op = ADD;
                break;
            case '1':
                test_proc_2_arg.op = SUB;
                break;
            case '2':
                test_proc_2_arg.op = MUL;
                break;
            case '3':
                test_proc_2_arg.op = DIV;
                break;
            default:
                printf("error:operate/n");
                exit(1);
        }
        printf("input the first number:");
        scanf("%f", &test_proc_2_arg.arg1);
        
        printf("input the second number:");
        scanf("%f", &test_proc_2_arg.arg2);
        /* -<<< Add to test*/
        
#ifndef	DEBUG
	clnt = clnt_create (host, TEST_PROG, TEST_VER, "udp");
	if (clnt == NULL) {
		printf("The clnt_create return null %p \n", clnt);
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = test_proc_2(&test_proc_2_arg, clnt);
	if (result_1 == (struct TEST *) NULL) {
		printf("The test_proc_2 return null %p \n", result_1);
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	
	/* -<<< Add to test*/
	printf("The result is %.2f \n", result_1->result);
	/* -<<< Add to test*/
}



int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	test_prog_2 (host);
exit (0);
}
