/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    // alias(libs.plugins.jvm)
    // kotlin("jvm") version "1.9.20"
    id("org.jetbrains.kotlin.jvm") version "1.9.20"

    // https://github.com/openjfx/javafx-gradle-plugin
    id("org.openjfx.javafxplugin") version "0.0.13"

    id("org.javamodularity.moduleplugin") version "1.8.12"
    id("org.beryx.jlink") version "2.25.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

javafx {
    version = "17"  // Specify JavaFX version
    modules ("javafx.controls", "javafx.fxml", 
             "javafx.web", "javafx.swing" , "javafx.media")
    
    //configuration = "implementation" // set dependency scope
    //configurations("implementation", "testImplementation")
}

jlink {
    // options = ["--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"]
    launcher {
        // javaHome = "c:/jdk-17"
        name = "hi_javafx"
    }
}

dependencies {

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.20")

    // implementation("org.controlsfx:controlsfx:11.1.2")
    // implementation("com.dlsc.formsfx:formsfx-core:11.6.0") {
    //     exclude(group = "org.openjfx")
    // }
    // implementation("net.synedra:validatorfx:0.4.0") {
    //     exclude(group = "org.openjfx")
    // }
    // implementation("org.kordamp.ikonli:ikonli-javafx:12.3.1")
    // implementation("org.kordamp.bootstrapfx:bootstrapfx-core:0.4.0")
    // implementation("eu.hansolo:tilesfx:11.48") {
    //     exclude(group = "org.openjfx")
    // }
    // implementation("com.github.almasb:fxgl:17.3") {
    //     exclude(group = "org.openjfx")
    //     exclude(group = "org.jetbrains.kotlin")
    // }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "hi_javafx.App"
    mainModule.set("hi_javafx")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

