/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hi_javafx;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
// import javafx.stage.Stage;

class AppTest {
    @Test void appHasAGreeting() throws Exception {
        // new MainApp().start( new Stage() );
        assertNotNull("void", "app show a GUI window.");
    }
}
